// constants for basicinfo
export const LOAD_USER_DETAILS = 'LOAD_USER_DETAILS'

// constants for dashboard
export const UPDATE_DASHBOARD = 'UPDATE_DASHBOARD'

// constants for pages
export const FETCH_PAGES_LIST = 'FETCH_PAGES_LIST'
export const FETCH_CONNECTED_PAGES_LIST = 'FETCH_CONNECTED_PAGES_LIST'

// constants for subscribers
export const FETCH_SUBSCRIBERS = 'FETCH_SUBSCRIBERS'
export const FETCH_SUBSCRIBERS_OVERRIDE = 'FETCH_SUBSCRIBERS_OVERRIDE'
export const UPDATE_SUBSCRIBER_PICTURE = 'UPDATE_SUBSCRIBER_PICTURE'

// constants live chat
export const UPDATE_CHAT_SESSIONS = 'UPDATE_CHAT_SESSIONS'
export const RESET_UNREAD_SESSION = 'RESET_UNREAD_SESSION'
export const SHOW_CHAT_SESSIONS = 'SHOW_CHAT_SESSIONS'
export const SHOW_OPEN_CHAT_SESSIONS = 'SHOW_OPEN_CHAT_SESSIONS'
export const SHOW_OPEN_CHAT_SESSIONS_OVERWRITE = 'SHOW_OPEN_CHAT_SESSIONS_OVERWRITE'
export const SHOW_CLOSE_CHAT_SESSIONS = 'SHOW_CLOSE_CHAT_SESSIONS'
export const SHOW_CLOSE_CHAT_SESSIONS_OVERWRITE = 'SHOW_CLOSE_CHAT_SESSIONS_OVERWRITE'
export const SHOW_USER_CHAT = 'SHOW_USER_CHAT'
export const SHOW_USER_CHAT_OVERWRITE = 'SHOW_USER_CHAT_OVERWRITE'
export const SOCKET_UPDATE = 'SOCKET_UPDATE'
export const SOCKET_UPDATE_SEEN = 'SOCKET_UPDATE_SEEN'
export const RESET_SOCKET = 'RESET_SOCKET'
export const LOADING_URL_META = 'LOADING_URL_META'
export const GET_URL_META = 'GET_URL_META'
export const UPDATE_CHAT = 'UPDATE_CHAT'
export const CHANGE_STATUS = 'CHANGE_STATUS'
export const SET_ACTIVE_SESSION = 'SET_ACTIVE_SESSION'
export const RESET_ACTIVE_SESSION = 'RESET_ACTIVE_SESSION'
export const SHOW_SEARCH_CHAT = 'SHOW_SEARCH_CHAT'
export const UPDATE_USER_CHAT = 'UPDATE_USER_CHAT'
export const CLEAR_SEARCH_RESULT = 'CLEAR_SEARCH_RESULT'
export const SHOW_CUSTOMERS = 'SHOW_CUSTOMERS'
export const UPDATE_OPEN_SESSIONS_WITH_CUSTOMERID = 'UPDATE_OPEN_SESSIONS_WITH_CUSTOMERID'
export const UPDATE_CLOSE_SESSIONS_WITH_CUSTOMERID = 'UPDATE_CLOSE_SESSIONS_WITH_CUSTOMERID'
export const UPDATE_SESSIONS = 'UPDATE_SESSIONS'
export const EMPTY_SOCKET_DATA = 'EMPTY_SOCKET_DATA'
export const CLEAR_USER_CHAT = 'CLEAR_USER_CHAT'
export const UPDATE_LIVECHAT_INFO = 'UPDATE_LIVECHAT_INFO'
export const UPDATE_SESSION_PROFILE_PICTURE = 'UPDATE_SESSION_PROFILE_PICTURE'

// constants for members
export const LOAD_MEMBERS = 'LOAD_MEMBERS'

// constants for teams
export const SHOW_TEAMS_LIST = 'SHOW_TEAMS_LIST'
